apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: kapp-sops-test
spec:
  serviceAccountName: tap-install-gitops-sa
  fetch:
  - git:
      url: https://github.com/Mpluya/kapp-sops-test
      ref: origin/main
      subPath: dontlook
  template:
  - sops:
      age:
        privateKeysSecretRef:
          name: age-key
  deploy:
  - kapp: {}
